version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: collabhub-postgres
    environment:
      POSTGRES_DB: collabhub
      POSTGRES_USER: collabhub
      POSTGRES_PASSWORD: collabhub_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - collabhub-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: collabhub-backend
    environment:
      DATABASE_URL: postgresql://collabhub:collabhub_password@postgres:5432/collabhub
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 4000
      SOCKET_PORT: 4001
    depends_on:
      - postgres
    ports:
      - "4000:4000"
      - "4001:4001"
    networks:
      - collabhub-network
    command: >
      sh -c "npx prisma migrate deploy &&
              npx prisma generate &&
              npm start"

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: collabhub-frontend
    environment:
      VITE_API_URL: http://localhost:4000
      VITE_SOCKET_URL: http://localhost:4001
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - collabhub-network

volumes:
  postgres_data:

networks:
  collabhub-network:
    driver: bridge 